### ISSUE TITLE
Add the ability to rerun only failing rspec test

### ISSUE THREAD

**Issue by benoittgt** [alexch/rerun#77]
Hello 

On the last rspec 3.3. You have the ability to run only failing test. I was thinking about adding the ability to rerun failing test. For exemple, you have your test running, you press `f` and command rerun with  `--only-failures` option.

http://rspec.info/blog/2015/06/rspec-3-3-has-been-released/

What are you thinking of this ?

**Comment by alexch** [comment]
I think it's a nice idea, and here's a way to do it:

```
rspec ; rerun -- rspec --only-failures
```

So the first part will populate your list-of-tests file, and the second part will keep running the failures again and again until there's none left. The only thing missing is running *all* of them again once they all pass... since in fixing one test you might have broken another.

(Yes, I call them tests, not specs or examples. Because that's what they are: tests. Also, get off my lawn. :-) )
